### PR TITLE
Update bash block structure

### LINKED ISSUE #55: use three-ticks bash block instead of ~~~
I think we've started using 

    ```bash

now (just to keep it standard). If you use this markup, it'd be `.language-bash` instead of `.source` but it's probably to keep everything standardized anyway

_Originally posted by @klieret in https://github.com/hsf-training/hsf-training-singularity-webpage/pull/52#discussion_r964887831_

### PR DESCRIPTION
**Pull request by amanmdesai**
**TO DO**
- [x] Episode 1
- [x] Episode 2
- [x] Episode 5

Closes #55

### CODE REVIEW

**Comment by amanmdesai** [comment]
I still need to update episodes 1, 4 (which are currently included in other PRs)

**Review by michmx — APPROVED** [review]

**Comment by amanmdesai** [comment]
episode 1 does not have bash blocks

**Comment by amanmdesai** [comment]
episode 4 i believe will  be done with #50

**Comment by amanmdesai** [comment]
@klieret this is ready for  review

**Review by klieret — APPROVED** [review]
LGTM!

**Pull request merged**
